// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission04.Models;

namespace Mission04.Migrations
{
    [DbContext(typeof(MovieSubmissionContext))]
    partial class MovieSubmissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission04.Models.MovieSubmission", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Drama",
                            Director = "Denis Villeneuve",
                            Edited = false,
                            LentTo = "",
                            Notes = "An amazing film",
                            Rating = "R",
                            Title = "Prisoners",
                            Year = 2013
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Drama",
                            Director = "Denis Villeneuve",
                            Edited = false,
                            LentTo = "",
                            Notes = "Another amazing film",
                            Rating = "R",
                            Title = "Sicario",
                            Year = 2015
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Drama",
                            Director = "Denis Villeneuve",
                            Edited = false,
                            LentTo = "",
                            Notes = "An amazing alien film",
                            Rating = "R",
                            Title = "Arrival",
                            Year = 2016
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
